---
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: line-length-limit
        severity: error
        arguments: [88]
      - name: unhandled-error
        arguments: ["fmt.Printf"]
